#!/bin/sh
./$* > $1.output
if [ ! -f $1.result ]
then
  echo fichier $1.result absent, je ne peux verifier les resultats
  exit 1
fi
if [ -n "`diff $1.output $1.result`" ]
then
    echo "Échec de $1: Verifiez votre programme ou utilisez le debugger."
else
    echo "SUCCES de $1: Vous pouvez passer a l'exercice suivant."
fi
